name: passcode
description: Challenge-response OTP library using SHA3-KMAC and BLAKE3 algorithms
version: 1.0.0
homepage: https://github.com/snowmerak/passcode

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  wasm_interop: ^2.0.0
  js: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
