[package]
name = "passcode-wasm"
version = "1.0.0"
edition = "2021"
authors = ["snowmerak"]
description = "WebAssembly bindings for Passcode OTP library"
license = "MIT"
repository = "https://github.com/snowmerak/passcode"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
passcode = { path = "../rust" }
wasm-bindgen = "0.2"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
strip = true        # Strip symbols from binary

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory"]
