[package]
name = "passcode"
version = "1.0.0"
edition = "2021"
authors = ["snowmerak"]
description = "Challenge-Response based One-Time Password (OTP) authentication library"
license = "MIT"
repository = "https://github.com/snowmerak/passcode"
keywords = ["otp", "authentication", "2fa", "challenge-response", "cryptography"]
categories = ["authentication", "cryptography"]

[dependencies]
sha3 = "0.10"
blake3 = "1.5"
hex = "0.4"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
rand = "0.8"
